name: wow

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wow-be
    depends_on:
      redis:
        condition: service_healthy
    environment:
      CACHE_URL: redis://redis:6379
    ports:
      - 3000:3000
    networks:
      - wownet

  redis:
    image: redis:7.2-alpine
    container_name: redis-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - wownet

networks:
  wownet:
    driver: bridge
