name: CI/CD to Railway

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
          CACHE_URL_TEST: ${{ secrets.CACHE_URL_TEST }}
          MAILER_USERNAME_TEST: ${{ secrets.MAILER_USERNAME_TEST }}
          MAILER_PASSWORD_TEST: ${{ secrets.MAILER_PASSWORD_TEST }}
          MAILER_RELAY_MAIL_TEST: ${{ secrets.MAILER_RELAY_MAIL_TEST }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: cargo test --verbose

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.com/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SVC_ID: ${{ secrets.SVC_ID }}
        run: |
          if [ -n "${SVC_ID}" ]; then
            railway up --service "${SVC_ID}" --environment "${RAILWAY_ENVIRONMENT_ID}" 
          else
            railway up --environment "${RAILWAY_ENVIRONMENT_ID}"
          fi
